### ISSUE TITLE
 I can't find the file curtayn.py

### ISSUE THREAD

**Issue by matata86** [Brephlas/dirty-slow-curtain3#1]
![image](https://github.com/Brephlas/dirty-slow-curtain3/assets/28623294/3f5b7756-0472-42c7-a789-421b05e8234f)
Hi, I'm following up on our conversation on the HA community.
Here is the terminal listing. I can't find the file. What am I doing wrong?
Thank you.

**Comment by Brephlas** [comment]
Oh might be the wrong integration I suggested. Not sure if this is limited in some form but you can also try the advanced one <https://github.com/hassio-addons/addon-ssh>
Also I'm not sure if you need to disable the secured moded in this integration (I've tried to find the file with enabled secured mode and it was possible) 


Btw on which version of home assistant are you?

**Comment by matata86** [comment]
Thank you for reply.
![image](https://github.com/Brephlas/dirty-slow-curtain3/assets/28623294/5b652fd8-7060-4e5b-8cec-3eaf3620b43a)

When I download the created complete Ha backup and look into the deps folder, it's also empty.

**Comment by Brephlas** [comment]
Unfortunately, I am out of ideas. 
During googling for site-package locations I found `/config/debs/libs` and `/usr/local/lib`.
However, /homeassistant is a link to /config and the command find should be able to find it either way

**Comment by quenthal** [comment]
I'm running Home Assistant in container. Could it be @matata86 same for you? EDIT: Just checked your screenshots, you are running complete Home Assistant OS, not the same as me.

But for those running HA in container, this should be valid. 

You need to bash inside to container. Within the container the localtion of curtain.py is:
`/usr/local/lib/python3.11/site-packages/switchbot/devices`

EDIT: `/usr/local/lib/python3.12/site-packages/switchbot/devices` as of now

**Comment by Brephlas** [comment]
@matata86 were you able to resolve this?
As quenthal mentioned, you should be able to modify the file inside the docker container `homeassistant`. Since I had the same issue now with HA2024.2, I updated the README and also could confirm that replacing the file inside the docker works.

**Comment by Ypi3** [comment]
Need to disable protection mode in Advanced SSH & Web Terminal.

Then you can list dockers with command
`docker ps`

Find docker column NAMES called homeassistant. Run docker with command.
`docker exec -it <container_id> /bin/bash`
